# Generated by Django 4.0.6 on 2022-07-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdditionalInfo', models.CharField(max_length=1000)),
                ('Reasons', models.CharField(max_length=1000)),
                ('CompanyName', models.CharField(max_length=100)),
                ('Symbol', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=1000)),
                ('LetterCode', models.CharField(max_length=20)),
                ('SentDateTime', models.CharField(max_length=100)),
                ('PublishDateTime', models.CharField(max_length=100)),
                ('TracingNo', models.IntegerField(default=0)),
                ('HasAttachment', models.BooleanField(default=False)),
                ('HasHtml', models.BooleanField(default=False)),
                ('HasXbrl', models.BooleanField(default=False)),
                ('IsEstimate', models.BooleanField(default=False)),
                ('Url', models.SlugField(max_length=200)),
                ('PdfUrl', models.SlugField(max_length=200)),
                ('ExcelUrl', models.SlugField(max_length=200)),
                ('AttachmentUrl', models.SlugField(max_length=200)),
                ('UnderSupervision', models.IntegerField(default=0)),
                ('HasExcel', models.BooleanField(default=False)),
                ('HasPdf', models.BooleanField(default=False)),
                ('XbrlUrl', models.SlugField(max_length=200)),
                ('TedanUrl', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SuperVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdditionalInfo', models.CharField(max_length=1000, null=True)),
                ('Reasons', models.CharField(max_length=1000)),
                ('UnderSupervision', models.IntegerField(default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notifications')),
            ],
        ),
    ]
